### PR TITLE
Create hassfest.yaml

### PR DESCRIPTION
**Pull request by gerard33**
Hassfest for custom components
See more info here -> https://developers.home-assistant.io/blog/2020/04/16/hassfest/

### CODE REVIEW

**Comment by gerard33** [comment]
I see Actions are disabled in your repo, so that would mean this check is not running yet.

**Comment by hakana** [comment]
What do you mean Actions are disabled?

**Comment by gerard33** [comment]
Usually there is an Action tab in the repo visible, but not in your repo.
 
In the settings of your Github repo there is a tab Actions. I guess you have disabled Actions there, which means hassfest wont run.

**Comment by hakana** [comment]
Now actions is enabled, it was disabled on the organization level.

**Comment by gerard33** [comment]
I see, the Action should run tonight so let's watch the results tomorrow :smiley:

**Pull request merged**
